spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/kodluyoruz
    username: postgre
    password: postgre
    driver-class-name: org.postgresql.Driver
  jpa:
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQL95Dialect
    show-sql: true
    hibernate:
      ddl-auto: update
